dependencies:
- name: wordpress
  version: 5.0.2
  repository: https://kubernetes-charts.storage.googleapis.com
- name: oauth2-proxy
  version: 3.2.1
  repository: https://kubernetes-charts.storage.googleapis.com