mariadb:
  enabled: false
ingress:
  enabled: true
  path: /
  hosts:
    - auth.int.ally.software
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: oauth2-proxy-https-cert
      hosts:
        - auth.int.ally.software

wordpress:
  wordpressPassword: foo
  mariadb:
    enabled: false
  externalDatabase:
    host: localhost
    user: bn_wordpress
    password: ""
    database: bitnami_wordpress
    port: 3306