mariadb:
  enabled: false

oauth2-proxy:
  ingress:
    enabled: true

wordpress:
  wordpressPassword: foo
  mariadb:
    enabled: false
  externalDatabase:
    host: localhost
    user: bn_wordpress
    password: ""
    database: bitnami_wordpress
    port: 3306